function [fitresult, gof] = fraunhofer_model_fit(t, intensities)
%CREATEFIT(T,INTENSITIES)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t
%      Y Output: intensities
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-Mar-2019 17:27:02


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t, intensities );

% Set up fittype and options.
ft = fittype( '2*z * (pi() * k)^-1 .* x.^-2 .* sin( w .* k .* x .* (2 * z)^-1).^2', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Algorithm = 'Levenberg-Marquardt';
opts.Display = 'Off';
opts.StartPoint = [0.7655 0.795199901137063 0.186872604554379];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'intensities vs. t', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel t
ylabel intensities
grid on


